#!/usr/bin/env bash

SERVER_NAME=$(hostname)
MATRIX_HOME=/opt/matrix
MATRIX_CONF=${MATRIX_HOME}/conf.d

mkdir -p ${MATRIX_CONF} ${MATRIX_HOME}/log

if mdata-get matrix_server_name >/dev/null 2>&1; then
	SERVER_NAME=$(mdata-get matrix_server_name)
fi

log "Generate homeserver.yaml config"
sudo -u matrix \
generate_config \
	--config-dir ${MATRIX_HOME} \
	--data-dir ${MATRIX_HOME}/data \
	--server-name ${SERVER_NAME} \
	--report-stats no \
	--output-file ${MATRIX_HOME}/homeserver.yaml

log "Install matrix synapse key signing key file"
MATRIX_SIGNING_KEY_FILE=${MATRIX_HOME}/${SERVER_NAME}.signing.key
if mdata-get matrix_signing_key >/dev/null 2>&1; then
	mdata-get matrix_signing_key > ${MATRIX_SIGNING_KEY_FILE}
else
	log "Key file doesn't exists, generating it"
	sudo -u matrix \
		python -m synapse.app.homeserver \
	                  -c ${MATRIX_HOME}/homeserver.yaml \
	                  --generate-keys
	cat ${MATRIX_SIGNING_KEY_FILE} | mdata-put matrix_signing_key
fi

log "Additional base_url needed based on the server_name"
cat > ${MATRIX_CONF}/base_url.yaml <<-EOF
public_baseurl: https://${SERVER_NAME}
EOF

log "Fix logging file generated by generate_config"
gsed -i -e "s|\(filename:\) .*|\1 ${MATRIX_HOME}/log/homeserver.log|g" \
	${MATRIX_HOME}/${SERVER_NAME}.log.config

log "Generate config file for pgsql connection"
cat > ${MATRIX_CONF}/database.yaml <<-EOF
database:
    name: psycopg2
    args:
        user: synapse
        password: $(mdata-get synapse_pgsql_pw)
        database: synapse
        host: localhost
        cp_min: 5
        cp_max: 10
EOF

if mdata-get mail_adminaddr >/dev/null 2>&1; then
log "Generate config for admin contact details"
cat > ${MATRIX_CONF}/admin.yaml <<-EOF
admin_contact: 'mailto:$(mdata-get mail_adminaddr)'
EOF
fi

if mdata-get mail_smarthost >/dev/null 2>&1 && \
   mdata-get mail_auth_user >/dev/null 2>&1; then
log "Generate config for email setup"
cat > ${MATRIX_CONF}/email.yaml <<-EOF
email:
    enable_notifs: true
    smtp_host: $(mdata-get mail_smarthost)
    smtp_port: 25
    smtp_user: $(mdata-get mail_auth_user)
    smtp_pass: $(mdata-get mail_auth_pass)
    require_transport_security: True
    notif_from: "Matrix %(app)s Home Server <noreply@${SERVER_NAME}>"
    notif_template_html: notif_mail.html
    notif_template_text: notif_mail.txt
EOF
fi

log "Generate and store secrets for matrix server"
MATRIX_REGISTRATION_SHARED_SECRET=$(/opt/core/bin/mdata-create-password.sh -m matrix_registration_shared_secret -e)
MATRIX_MACAROON_SECRET_KEY=$(/opt/core/bin/mdata-create-password.sh -m matrix_macaroon_secret_key -e)
cat > ${MATRIX_CONF}/secret.yaml <<-EOF
registration_shared_secret: ${MATRIX_REGISTRATION_SHARED_SECRET}
macaroon_secret_key: ${MATRIX_MACAROON_SECRET_KEY}
EOF

log "Fix permissions for all files stored in ${MATRIX_HOME}"
chown -R matrix:matrix ${MATRIX_HOME}
