#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

MATRIX_SYNAPSE_VERSION=1.19.1
RIOT_WEB_VERSION=1.7.7
RIOT_WEB_URL="https://github.com/vector-im/element-web/releases/download/v${RIOT_WEB_VERSION}/riot-v${RIOT_WEB_VERSION}.tar.gz"

# Munin plugins
MUNIN_PLUGINS="
"

# Exit if any commands fail
set -o errexit

echo "* Use default python 3.7"
pkg_alternatives manual python37
pkg_alternatives manual py37-pip

echo "* Remove used pgsql stuff from base"
rm -rf /var/pgsql/*

echo "* Install matrix synapse"
pip install matrix-synapse==${MATRIX_SYNAPSE_VERSION}

echo "* Create matrix-synapse user and home folder"
mkdir -p /opt/matrix
groupadd matrix
useradd -g matrix -s /usr/bin/bash -c "Matrix Synapse" -d /opt/matrix matrix
passwd -u matrix

echo "* Download and extract element web interface"
mkdir -p /var/www
curl -L "${RIOT_WEB_URL}" | gtar xz -C /var/www --strip-components=1

echo "* Fix home permissions for matrix user and web-root"
chown -R matrix:matrix /opt/matrix
chown -R www:www /var/www

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
