#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

WEB_VERSION=1.11.25
WEB_URL="https://github.com/vector-im/element-web/releases/download/v${WEB_VERSION}/element-v${WEB_VERSION}.tar.gz"

# Munin plugins
MUNIN_PLUGINS="
"

# Exit if any commands fail
set -o errexit

echo "* Remove used pgsql stuff from base"
rm -rf /var/pgsql/*

echo "* Download and extract element web interface"
mkdir -p /var/www
curl -L "${WEB_URL}" | gtar xz -C /var/www --strip-components=1

echo "* Fix home permissions for web-root"
chown -R www:www /var/www


echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
